"""
Mesh deformer — Phase 2, Week 7.

Takes a base car (generated by model_generator.py) and applies team-specific
geometric deformations so each constructor has a visually distinct profile.

Deformation approach: per-component scale + translate overrides.
These are fed into generate_car_glb(deform_params=...) rather than post-
processing a finished mesh, which avoids mesh corruption and keeps the
pipeline simple.

Each team profile describes:
  - sidepod_concept: "downwash" | "undercut" | "slim" | "conventional"
  - nose_style: "narrow" | "wide" | "anteater"
  - rear_wing: "high_downforce" | "low_drag" | "standard"

The deform_params dict maps component node names → {"scale": [sx,sy,sz], "translate": [dx,dy,dz]}
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

# ── Team design profiles ───────────────────────────────────────────────────────

@dataclass
class TeamDesignProfile:
    team_id: str
    sidepod_concept: Literal["downwash", "undercut", "slim", "conventional"]
    nose_style:      Literal["narrow", "wide", "anteater"]
    rear_wing:       Literal["high_downforce", "low_drag", "standard"]
    notes: str = ""


TEAM_PROFILES: dict[str, TeamDesignProfile] = {
    "red-bull": TeamDesignProfile(
        team_id="red-bull",
        sidepod_concept="downwash",
        nose_style="narrow",
        rear_wing="low_drag",
        notes="Slim downwash sidepods, narrow pullrod nose, low-drag rear wing",
    ),
    "ferrari": TeamDesignProfile(
        team_id="ferrari",
        sidepod_concept="conventional",
        nose_style="wide",
        rear_wing="high_downforce",
        notes="Conventional sidepods, wide nose, high-downforce rear wing package",
    ),
    "mercedes": TeamDesignProfile(
        team_id="mercedes",
        sidepod_concept="undercut",
        nose_style="narrow",
        rear_wing="standard",
        notes="Zero-pod / undercut sidepod concept, narrow nose",
    ),
    "mclaren": TeamDesignProfile(
        team_id="mclaren",
        sidepod_concept="slim",
        nose_style="narrow",
        rear_wing="low_drag",
        notes="Mini-pod concept, slim sidepods for high-speed circuits",
    ),
    "aston-martin": TeamDesignProfile(
        team_id="aston-martin",
        sidepod_concept="conventional",
        nose_style="wide",
        rear_wing="high_downforce",
        notes="Conventional layout optimised for downforce",
    ),
    "alpine": TeamDesignProfile(
        team_id="alpine",
        sidepod_concept="conventional",
        nose_style="narrow",
        rear_wing="standard",
        notes="Standard layout, moderate downforce",
    ),
    "williams": TeamDesignProfile(
        team_id="williams",
        sidepod_concept="undercut",
        nose_style="narrow",
        rear_wing="low_drag",
        notes="Undercut sidepods, efficiency-focused aero",
    ),
    "racing-bulls": TeamDesignProfile(
        team_id="racing-bulls",
        sidepod_concept="downwash",
        nose_style="narrow",
        rear_wing="standard",
        notes="Derived from Red Bull concept with downwash sidepods",
    ),
    "haas": TeamDesignProfile(
        team_id="haas",
        sidepod_concept="conventional",
        nose_style="wide",
        rear_wing="high_downforce",
        notes="Conventional layout, Ferrari-influenced",
    ),
    "audi": TeamDesignProfile(
        team_id="audi",
        sidepod_concept="slim",
        nose_style="narrow",
        rear_wing="standard",
        notes="Clean, slim sidepod package under new ownership",
    ),
    "cadillac": TeamDesignProfile(
        team_id="cadillac",
        sidepod_concept="conventional",
        nose_style="wide",
        rear_wing="high_downforce",
        notes="New entrant — conservative conventional layout",
    ),
}


# ── Scale presets per concept ──────────────────────────────────────────────────
# Scale vectors [sx, sy, sz] applied to component bounding box.
# Values near 1.0 = slight change; 0.7 = 30% reduction in that axis.

_SIDEPOD_SCALES = {
    "downwash":     [0.85, 0.82, 1.00],   # narrower + shorter sidepods
    "undercut":     [0.80, 0.75, 1.00],   # aggressively undercut
    "slim":         [0.78, 0.88, 0.95],   # narrow and slightly shorter
    "conventional": [1.00, 1.00, 1.00],   # base shape
}

_SIDEPOD_INLET_SCALES = {
    "downwash":     [0.80, 0.85, 1.0],
    "undercut":     [0.85, 0.70, 1.0],
    "slim":         [0.75, 0.80, 1.0],
    "conventional": [1.00, 1.00, 1.0],
}

_NOSE_SCALES = {
    "narrow":   [0.80, 0.90, 1.00],
    "wide":     [1.10, 1.00, 1.00],
    "anteater": [0.60, 0.75, 1.00],
}

_RW_SCALES = {
    "high_downforce": [1.00, 1.15, 1.10],   # taller, more chord
    "low_drag":       [0.95, 0.88, 0.90],   # lower, less chord
    "standard":       [1.00, 1.00, 1.00],
}

_RW_FLAP_SCALES = {
    "high_downforce": [1.00, 1.20, 1.10],
    "low_drag":       [0.95, 0.80, 0.90],
    "standard":       [1.00, 1.00, 1.00],
}


# ── Builder ────────────────────────────────────────────────────────────────────

def build_deform_params(team_id: str) -> dict[str, dict]:
    """
    Return a deform_params dict for generate_car_glb().

    Keys are component node names from model_generator.py.
    Values are dicts with optional "scale" and "translate" keys.
    """
    profile = TEAM_PROFILES.get(team_id)
    if not profile:
        return {}   # no deformation → base model

    params: dict[str, dict] = {}

    # Sidepods (both sides)
    sp_scale = _SIDEPOD_SCALES[profile.sidepod_concept]
    in_scale = _SIDEPOD_INLET_SCALES[profile.sidepod_concept]
    for side in ("l", "r"):
        params[f"sidepod_{side}"]       = {"scale": list(sp_scale)}
        params[f"sidepod_inlet_{side}"] = {"scale": list(in_scale)}

    # Nose cone
    nose_scale = _NOSE_SCALES[profile.nose_style]
    params["nose_cone"] = {"scale": list(nose_scale)}

    # Rear wing
    rw_scale  = _RW_SCALES[profile.rear_wing]
    flp_scale = _RW_FLAP_SCALES[profile.rear_wing]
    params["rw_main"] = {"scale": list(rw_scale)}
    params["rw_flap"] = {"scale": list(flp_scale)}
    for side in ("l", "r"):
        params[f"rw_endplate_{side}"] = {"scale": list(rw_scale)}

    return params


def deform_description(team_id: str) -> str:
    """Human-readable summary of the team's design concept."""
    p = TEAM_PROFILES.get(team_id)
    if not p:
        return "Standard base configuration"
    return (
        f"Sidepod concept: {p.sidepod_concept} | "
        f"Nose: {p.nose_style} | "
        f"Rear wing: {p.rear_wing}"
    )
